
export const GET_HOME_BANNERS_REQUEST = "GET_HOME_BANNERS_REQUEST"
export const GET_HOME_BANNERS_SUCCESS = "GET_HOME_BANNERS_SUCCESS"
export const GET_HOME_BANNERS_FAIL = "GET_HOME_BANNERS_FAIL"

export const CLEAR_HOME_BANNERS_SUCCESS = "CLEAR_HOME_BANNERS_SUCCESS"
export const CLEAR_HOME_BANNERS_ERROR = "CLEAR_HOME_BANNERS_ERROR"

