

export const GET_ALL_MESSAGE_REQUEST = "GET_ALL_MESSAGE_REQUEST"
export const GET_ALL_MESSAGE_SUCCESS = "GET_ALL_MESSAGE_SUCCESS"
export const GET_ALL_MESSAGE_FAIL = "GET_ALL_MESSAGE_FAIL"

export const CLEAR_MESSAGE_SUCCESS = "CLEAR_MESSAGE_SUCCESS"
export const CLEAR_MESSAGE_ERROR = "CLEAR_MESSAGE_ERROR"

