
export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST"
export const CREATE_NEW_ORDER_SUCCESS = "CREATE_NEW_ORDER_SUCCESS"
export const CREATE_NEW_ORDER_FAILED = "CREATE_NEW_ORDER_FAILED"

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAILED = "GET_ALL_ORDERS_FAILED"

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST"
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS"
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL"


export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED"





export const CLEAR_ORDER_SUCCESS = "CLEAR_ORDER_SUCCESS"
export const CLEAR_ORDER_ERROR = "CLEAR_ORDER_ERROR"




