

export const CREATE_PRODUCT_CATEGORY_REQUEST = "CREATE_PRODUCT_CATEGORY_REQUEST"
export const CREATE_PRODUCT_CATEGORY_SUCCESS = "CREATE_PRODUCT_CATEGORY_SUCCESS"
export const CREATE_PRODUCT_CATEGORY_FAIL = "CREATE_PRODUCT_CATEGORY_FAIL"

export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST"
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS"
export const GET_PRODUCT_CATEGORIES_FAIL = "GET_PRODUCT_CATEGORIES_FAIL"

export const GET_PRODUCT_CATEGORY_REQUEST = "GET_PRODUCT_CATEGORY_REQUEST"
export const GET_PRODUCT_CATEGORY_SUCCESS = "GET_PRODUCT_CATEGORY_SUCCESS"
export const GET_PRODUCT_CATEGORY_FAIL = "GET_PRODUCT_CATEGORY_FAIL"

export const EDIT_PRODUCT_CATEGORY_REQUEST = "EDIT_PRODUCT_CATEGORY_REQUEST"
export const EDIT_PRODUCT_CATEGORY_SUCCESS = "EDIT_PRODUCT_CATEGORY_SUCCESS"
export const EDIT_PRODUCT_CATEGORY_FAIL = "EDIT_PRODUCT_CATEGORY_FAIL"



export const CLEAR_PRODUCT_CATEGORY_SUCCESS = "CLEAR_PRODUCT_CATEGORY_SUCCESS"
export const CLEAR_PRODUCT_CATEGORY_ERROR = "CLEAR_PRODUCT_CATEGORY_ERROR"


