

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_FAIL = "EDIT_USER_FAIL"

export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST"
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS"
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL"

export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST"
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS"
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL"

// export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
// export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
// export const DELETE_USER_FAIL = "DELETE_USER_FAIL"


export const LOGGED_USER_REQUEST = "LOGGED_USER_REQUEST"
export const LOGGED_USER_SUCCESS = "LOGGED_USER_SUCCESS"
export const LOGGED_USER_FAIL = "LOGGED_USER_FAIL"

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const CLEAR_SUCCESS = "CLEAR_SUCCESS"
export const CLEAR_ERROR = "CLEAR_ERROR"

